### ISSUE TITLE
690 & 890 compatible?

### ISSUE THREAD

**Issue by iosdeveloper** [koalazak/dorita980#48]
Doesn't seem to work with the new 690. What about the 890?

**Comment by koalazak** [comment]
Hi, I dont know. I dont own a 690/980. Anybody try?

**Comment by iosdeveloper** [comment]
I checked with a 690 owner and it doesn't send the `pose` values.

**Comment by pschmitt** [comment]
But the rest works?

**Comment by iosdeveloper** [comment]
AFAIK, yes. No `pose` means no map though.

**Comment by pschmitt** [comment]
That actually makes sense since only the 980 and the 960 have a camera and have the map feature on their spec sheet. The 890 behave similarly to the 690.

- 690: https://store.irobot.com/default/roomba-vacuuming-robot-vacuum-irobot-roomba-690/R690020.html
- 890: https://store.irobot.com/default/roomba-vacuuming-robot-vacuum-irobot-roomba-890/R890020.html
- 960: https://store.irobot.com/default/roomba-vacuuming-robot-vacuum-irobot-roomba-960/R960020.html
- 980: https://store.irobot.com/default/roomba-vacuuming-robot-vacuum-irobot-roomba-980/R980020.html

**Comment by koalazak** [comment]
the only diference between 980 and 960 is the carpet bust and the battery.
here is the comparison chart:
http://www.irobot.com/For-the-Home/Vacuuming/Roomba.aspx#Comparison-Chart

**Comment by pschmitt** [comment]
@iosdeveloper What does the `cap` field contain?

For my Roomba 980 that'd be the following:
```python
[('pose', 1),
  ('ota', 2),
  ('multiPass', 2),
  ('carpetBoost', 1),
  ('pp', 1),
  ('binFullDetect', 1),
  ('langOta', 1),
  ('maps', 1),
  ('edge', 1),
  ('eco', 1),
  ('svcConf', 1)]
```

**Comment by maxbaeumle** [comment]
```"cap": {
    "eco": 1,
    "ota": 1,
    "svcConf": 1
}```

**Comment by iosdeveloper** [comment]
```
"cap": {
    "eco": 1,
    "ota": 1,
    "svcConf": 1
}
```

**Comment by pschmitt** [comment]
Oh so they are actually NOT set. Thanks for the info.
